### ISSUE TITLE
Implement firebase push notifications on transaction service

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-notification-service#70]
- [x] Logic to send push
- [x] Endpoint to set push token to Safes mapping (what about client id, client language, client version)

See epic for purpose: https://app.zenhub.com/workspace/o/gnosis/safe/issues/290

### Open Questions
- What is the public URL? (see https://gnosisinc.slack.com/archives/C63LQTGNB/p1596630084279400?thread_ts=1596621615.267200&cid=C63LQTGNB)

**Comment by sche** [comment]
So we will need to:
- register
- unregister (remove safe)
- select types of notifications (transaction submitted; transaction status update; Eth/Erc20/Erc721 received)

**Comment by DmitryBespalov** [comment]
@Uxio0  @tschubotz @gnosis/mobile-devs 

Our notifications to be implemented:
- outgoing transaction submitted to Ethereum; 
- outgoing transaction failed or succeeded; 
- ETH, ERC20, ERC721 received 

Configuration of the APNS + Android message  delivery options ([see documentation](https://firebase.google.com/docs/cloud-messaging/concept-options#delivery-options)):
-  **data message type**: because we want to get the information about transaction from the backend by the transaction hash and display appropriate localized message in  the app, the message type should be "Data message". If we would choose "Notification message" type, then it will be displayed immediately. (I'm  not 100% sure about this, needs to be tested).
- **"non-collapsible" (default)**:  Collapsible messages are intended for such cases as periodic sync from server. In our case, we need to deliver each message to the user, so the notification is needed to be non-collapsible, which is the default value. 
- **"normal" priority (default)**: For the notification types that we currently implement no user interaction is needed on the mobile, so I'd say it would be a normal priority, which is the default value.
- **"time to live" 4 weeks (default).**: For our to-be-implemented notification types, I think, there is no need to specify the expiration date, which will default to the maximum expiration date - 28 days. It is not a situation when user needs to act quickly, as, for example, in an VOIP application when user receives a call. Therefore, I'd propose to configure it as a default, too.

**Comment by rmeissner** [comment]
> outgoing transaction submitted to Ethereum

Could we specify this a little more. If there should be a push if an owner submitted the tx into the mempool for execution (so it is waiting to be mined) then this is out of scope.

**Comment by rmeissner** [comment]
What I feel is missing is that a new tx is waiting for confirmation

**Comment by tschubotz** [comment]
> What I feel is missing is that a new tx is waiting for confirmation

I took this out since we would only want to send this message to owners, right? So we would have to add access control etc. so I figured not needed right now

**Comment by tschubotz** [comment]
> Could we specify this a little more. If there should be a push if an owner submitted the tx into the mempool for execution (so it is waiting to be mined) then this is out of scope.

I thought it would be good to know when someone clicked "execute". But thinking about this more, I don't think we need this in a v1. Even less when you say it's hard, technically to do.

**Comment by rmeissner** [comment]
So waiting for confirmation is easy to do, but sending a push when a tx is submitted to a node for execution (into mempool, waiting to be mined) that is different

**Comment by tschubotz** [comment]
> but sending a push when a tx is submitted to a node for execution (into mempool, waiting to be mined) that is different

understood. Uxio actually commented on the Epic already, I missed that. Removed this from the epic already.

> So waiting for confirmation is easy to do

Yea but still, I think some access control should be present there imo. Hence, I would leave out for this v1.

**Comment by MouazAlzahabi** [comment]
I think it would be nice if we recognized also "Setting changes" tx, so we can display some notifications like "New owner added" or so

**Comment by tschubotz** [comment]
> I think it would be nice if we recognized also "Setting changes" tx, so we can display some notifications like "New owner added" or so

True. I added a proposal to gnosis/safe#290 and also added this to the agenda of the backlog refinement to see if we should split this up or not. Thanks for the suggestion.

**Comment by Uxio0** [comment]
@DmitryBespalov @sche @jpalvarezl @biafra23 @elgatovital Would you be ok with having an [UUID ](https://tools.ietf.org/html/rfc4122.html)for the device? That way I can link the `push tokens` to a device and know when that changed? I would need you to generate it yourselves and keep it for token registration/unregistration requests.

**Comment by DmitryBespalov** [comment]
@Uxio0 @gnosis/mobile-devs 

I think, we should go with Firebase Instance ID, as there's already API and Firebase handling the ID generation, refresh, and storage. 

Here are the options that I found

### Firebase Instance ID

[On Android](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId),

> Instance ID is stable except when:
> - App deletes Instance ID
> - App is restored on a new device
> - User uninstalls/reinstall the app
> - User clears app data

[On iOS](https://firebase.google.com/docs/reference/swift/firebaseinstanceid/api/reference/Classes/InstanceID)

> Instance  ID is long lived but, may be reset if the device is not used for a long time or the Instance ID service detects a problem. If Instance ID is reset, the app will be notified via `kFIRInstanceIDTokenRefreshNotification`.
> 
> If the Instance ID has become invalid, the app can request a new one and send it to the app server. To prove ownership of Instance ID and to allow servers to access data or services associated with the app, call `[FIRInstanceID tokenWithAuthorizedEntity:scope:options:handler]`.

So,  Firebase instance ID can change or  become invalid, while the app is still installed on the same device. That means that old ID is not usable anymore and it needs to be cleaned up somehow (preferrably from the server side, because we can only notify that the previous id became invalid if we know it, so it won't work on the app reinstall or device switch).

### iOS 'identifierForVendor'
iOS's `identifierForVendor` - identifier that is the same for all of the apps from the same company installed on the device. I would go for the Firebase's ID because it has same semantics on both platforms.

### Advertising Identifiers
`Advertising ID` on Android and `advertisingIdentifier`and iOS. This is not our use case, as we don't need to serve or track advertisements, so using this is discouraged.

### Our own generated UUID
Generating our own UUID inside the app and persisting it. This will not be the same across app installs/reinstalls. 

We need to be careful about backup, because if we store the ID on one device and it is restored on another device, the UUID will stay the same (unless we disallow it - on iOS it  is possible to specify if some data can be restored or not on the backup, not sure on Android).

## Other 
Note that  the push token can be refreshed. In the past, we were sending the current push token with the device info on every app start or when the push token was refreshed.

**Comment by Uxio0** [comment]
Hi @DmitryBespalov, I see your point, but that would be depending more on Firebase and trusting that they behave as they say and they are not changing or invalidating with no reason (as they do with the Cloud Messaging Tokens, for example).

Looking at all the problems we had with the old notifications service, I would prefer to rely in a UUID generated and keeped by ourselves, as I don't see any more advantage on using their own that not having to store it ourselves (unless I'm missing something)

**Comment by DmitryBespalov** [comment]
@Uxio0 that makes sense, as in the past Firebase was not reliable for push notifications, and tokens were invalidated 🤷 

I see your point and I think, our own generated UUID can be done.

@biafra23 @jpalvarezl can you please comment if there are any issues or challenges hiding for that solution on Android?
